// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	FoodID      int32            `json:"food_id"`
	UserID      pgtype.Int4      `json:"user_id"`
	FoodName    string           `json:"food_name"`
	Calories100 pgtype.Numeric   `json:"calories_100"`
	Protein100  pgtype.Numeric   `json:"protein_100"`
	Carbs100    pgtype.Numeric   `json:"carbs_100"`
	Fats100     pgtype.Numeric   `json:"fats_100"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}

type FoodCache struct {
	FoodID      int32            `json:"food_id"`
	UserID      pgtype.Int4      `json:"user_id"`
	FoodName    string           `json:"food_name"`
	IsSolid     pgtype.Bool      `json:"is_solid"`
	Calories100 pgtype.Numeric   `json:"calories_100"`
	Protein100  pgtype.Numeric   `json:"protein_100"`
	Carbs100    pgtype.Numeric   `json:"carbs_100"`
	Fats100     pgtype.Numeric   `json:"fats_100"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}

type FoodEntry struct {
	NutritionID int32            `json:"nutrition_id"`
	UserID      int32            `json:"user_id"`
	FoodID      pgtype.Int4      `json:"food_id"`
	RecipeID    pgtype.Int4      `json:"recipe_id"`
	Calories    pgtype.Numeric   `json:"calories"`
	TotalGrams  pgtype.Numeric   `json:"total_grams"`
	Protein     pgtype.Numeric   `json:"protein"`
	Carbs       pgtype.Numeric   `json:"carbs"`
	Fats        pgtype.Numeric   `json:"fats"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}

type Recipe struct {
	RecipeID     int32            `json:"recipe_id"`
	UserID       pgtype.Int4      `json:"user_id"`
	RecipeName   string           `json:"recipe_name"`
	Instructions pgtype.Text      `json:"instructions"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	LastUpdated  pgtype.Timestamp `json:"last_updated"`
}

type RecipeIngredient struct {
	IngredientID int32            `json:"ingredient_id"`
	RecipeID     int32            `json:"recipe_id"`
	FoodID       int32            `json:"food_id"`
	TotalGrams   pgtype.Numeric   `json:"total_grams"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	LastUpdated  pgtype.Timestamp `json:"last_updated"`
}

type Training struct {
	TrainingID   int32            `json:"training_id"`
	UserID       int32            `json:"user_id"`
	RoutineID    pgtype.Int4      `json:"routine_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	LastUpdated  pgtype.Timestamp `json:"last_updated"`
	ExerciseName pgtype.Text      `json:"exercise_name"`
	Notes        pgtype.Text      `json:"notes"`
}

type TrainingIngredient struct {
	TrainingEntryID int32          `json:"training_entry_id"`
	UserID          int32          `json:"user_id"`
	RoutineID       pgtype.Int4    `json:"routine_id"`
	ExerciseName    pgtype.Text    `json:"exercise_name"`
	Weight          pgtype.Numeric `json:"weight_"`
	Sets            int32          `json:"sets_"`
	Reps            int32          `json:"reps"`
	Notes           pgtype.Text    `json:"notes"`
}

type TrainingRoutine struct {
	RoutineID           int32            `json:"routine_id"`
	UserID              int32            `json:"user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	LastUpdated         pgtype.Timestamp `json:"last_updated"`
	TrainingRoutineName pgtype.Text      `json:"training_routine_name"`
	Notes               pgtype.Text      `json:"notes"`
}

type User struct {
	UserID         int32            `json:"user_id"`
	Username       string           `json:"username"`
	Email          string           `json:"email"`
	HashedPassword string           `json:"hashed_password"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type UsersProfile struct {
	UserID      int32            `json:"user_id"`
	DateOfBirth pgtype.Date      `json:"date_of_birth"`
	Height      pgtype.Numeric   `json:"height"`
	Weight      pgtype.Numeric   `json:"weight"`
	IsTrainer   bool             `json:"is_trainer"`
	IsVip       bool             `json:"is_vip"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}
