// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateFoodCacheItem(ctx context.Context, arg CreateFoodCacheItemParams) (FoodCache, error)
	CreateFoodItem(ctx context.Context, arg CreateFoodItemParams) (CreateFoodItemRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	LogExercise(ctx context.Context, arg LogExerciseParams) (ExerciseEntry, error)
	LogFoodItem(ctx context.Context, arg LogFoodItemParams) (FoodEntry, error)
	ViewFood(ctx context.Context, arg ViewFoodParams) ([]ViewFoodRow, error)
	ViewFoodTotal(ctx context.Context, arg ViewFoodTotalParams) (ViewFoodTotalRow, error)
}

var _ Querier = (*Queries)(nil)
