// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodCacheItem = `-- name: CreateFoodCacheItem :one
INSERT INTO food_Cache(user_id,food_name,calories_100,protein_100,carbs_100,fats_100)
VALUES($1,$2,$3,$4,$5,$6)
RETURNING food_id, user_id, food_name, calories_100, protein_100, carbs_100, fats_100, created_at, last_updated
`

type CreateFoodCacheItemParams struct {
	UserID      int64   `json:"user_id"`
	FoodName    string  `json:"food_name"`
	Calories100 float64 `json:"calories_100"`
	Protein100  float64 `json:"protein_100"`
	Carbs100    float64 `json:"carbs_100"`
	Fats100     float64 `json:"fats_100"`
}

func (q *Queries) CreateFoodCacheItem(ctx context.Context, arg CreateFoodCacheItemParams) (FoodCache, error) {
	row := q.db.QueryRow(ctx, createFoodCacheItem,
		arg.UserID,
		arg.FoodName,
		arg.Calories100,
		arg.Protein100,
		arg.Carbs100,
		arg.Fats100,
	)
	var i FoodCache
	err := row.Scan(
		&i.FoodID,
		&i.UserID,
		&i.FoodName,
		&i.Calories100,
		&i.Protein100,
		&i.Carbs100,
		&i.Fats100,
		&i.CreatedAt,
		&i.LastUpdated,
	)
	return i, err
}

const createFoodItem = `-- name: CreateFoodItem :one
INSERT INTO food(user_id,food_name,calories_100,protein_100,carbs_100,fats_100)
VALUES($1,$2,$3,$4,$5,$6)
RETURNING user_id,food_name,calories_100,protein_100,carbs_100,fats_100
`

type CreateFoodItemParams struct {
	UserID      int64   `json:"user_id"`
	FoodName    string  `json:"food_name"`
	Calories100 float64 `json:"calories_100"`
	Protein100  float64 `json:"protein_100"`
	Carbs100    float64 `json:"carbs_100"`
	Fats100     float64 `json:"fats_100"`
}

type CreateFoodItemRow struct {
	UserID      int64   `json:"user_id"`
	FoodName    string  `json:"food_name"`
	Calories100 float64 `json:"calories_100"`
	Protein100  float64 `json:"protein_100"`
	Carbs100    float64 `json:"carbs_100"`
	Fats100     float64 `json:"fats_100"`
}

func (q *Queries) CreateFoodItem(ctx context.Context, arg CreateFoodItemParams) (CreateFoodItemRow, error) {
	row := q.db.QueryRow(ctx, createFoodItem,
		arg.UserID,
		arg.FoodName,
		arg.Calories100,
		arg.Protein100,
		arg.Carbs100,
		arg.Fats100,
	)
	var i CreateFoodItemRow
	err := row.Scan(
		&i.UserID,
		&i.FoodName,
		&i.Calories100,
		&i.Protein100,
		&i.Carbs100,
		&i.Fats100,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password)
VALUES ($1, $2)
RETURNING user_id, username
`

type CreateUserParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

type CreateUserRow struct {
	UserID   int64  `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.HashedPassword)
	var i CreateUserRow
	err := row.Scan(&i.UserID, &i.Username)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id,username,hashed_password
FROM users
WHERE user_id = $1
`

type GetUserByIDRow struct {
	UserID         int64  `json:"user_id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(&i.UserID, &i.Username, &i.HashedPassword)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id,username, hashed_password
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	UserID         int64  `json:"user_id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.UserID, &i.Username, &i.HashedPassword)
	return i, err
}

const logExercise = `-- name: LogExercise :one
INSERT INTO exercise_entries(user_id,exercise_name,weight,sets,reps,rpe,notes)
VALUES($1,$2,$3,$4,$5,$6,$7)
RETURNING entry_id, user_id, created_at, last_updated, exercise_name, weight, sets, reps, rpe, notes
`

type LogExerciseParams struct {
	UserID       int64          `json:"user_id"`
	ExerciseName string         `json:"exercise_name"`
	Weight       pgtype.Numeric `json:"weight"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	Rpe          int32          `json:"rpe"`
	Notes        pgtype.Text    `json:"notes"`
}

func (q *Queries) LogExercise(ctx context.Context, arg LogExerciseParams) (ExerciseEntry, error) {
	row := q.db.QueryRow(ctx, logExercise,
		arg.UserID,
		arg.ExerciseName,
		arg.Weight,
		arg.Sets,
		arg.Reps,
		arg.Rpe,
		arg.Notes,
	)
	var i ExerciseEntry
	err := row.Scan(
		&i.EntryID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastUpdated,
		&i.ExerciseName,
		&i.Weight,
		&i.Sets,
		&i.Reps,
		&i.Rpe,
		&i.Notes,
	)
	return i, err
}

const logFoodItem = `-- name: LogFoodItem :one
INSERT INTO food_entries (
    user_id,
    food_id,
    recipe_id,
    calories,
    total_grams,
    protein,
    carbs,
    fats
) VALUES (
    $1,  -- user_id (BIGINT, NOT NULL)
    $2,  -- food_id (BIGINT, can be NULL)
    $3,  -- recipe_id (BIGINT, can be NULL) 
    $4,  -- calories (DOUBLE PRECISION, NOT NULL)
    $5,  -- total_grams (DOUBLE PRECISION, NOT NULL)
    $6,  -- protein (DOUBLE PRECISION, NOT NULL)
    $7,  -- carbs (DOUBLE PRECISION, NOT NULL)
    $8   -- fats (DOUBLE PRECISION, NOT NULL)
)
RETURNING nutrition_id, user_id, food_id, recipe_id, calories, total_grams, protein, carbs, fats, created_at, last_updated
`

type LogFoodItemParams struct {
	UserID     int64       `json:"user_id"`
	FoodID     pgtype.Int8 `json:"food_id"`
	RecipeID   pgtype.Int8 `json:"recipe_id"`
	Calories   float64     `json:"calories"`
	TotalGrams float64     `json:"total_grams"`
	Protein    float64     `json:"protein"`
	Carbs      float64     `json:"carbs"`
	Fats       float64     `json:"fats"`
}

func (q *Queries) LogFoodItem(ctx context.Context, arg LogFoodItemParams) (FoodEntry, error) {
	row := q.db.QueryRow(ctx, logFoodItem,
		arg.UserID,
		arg.FoodID,
		arg.RecipeID,
		arg.Calories,
		arg.TotalGrams,
		arg.Protein,
		arg.Carbs,
		arg.Fats,
	)
	var i FoodEntry
	err := row.Scan(
		&i.NutritionID,
		&i.UserID,
		&i.FoodID,
		&i.RecipeID,
		&i.Calories,
		&i.TotalGrams,
		&i.Protein,
		&i.Carbs,
		&i.Fats,
		&i.CreatedAt,
		&i.LastUpdated,
	)
	return i, err
}

const viewFood = `-- name: ViewFood :many
SELECT calories, protein, carbs, fats
FROM food_entries
WHERE user_id = $1 
  AND created_at BETWEEN $2 AND $3
ORDER BY created_at
`

type ViewFoodParams struct {
	UserID      int64            `json:"user_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

type ViewFoodRow struct {
	Calories float64 `json:"calories"`
	Protein  float64 `json:"protein"`
	Carbs    float64 `json:"carbs"`
	Fats     float64 `json:"fats"`
}

func (q *Queries) ViewFood(ctx context.Context, arg ViewFoodParams) ([]ViewFoodRow, error) {
	rows, err := q.db.Query(ctx, viewFood, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ViewFoodRow
	for rows.Next() {
		var i ViewFoodRow
		if err := rows.Scan(
			&i.Calories,
			&i.Protein,
			&i.Carbs,
			&i.Fats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewFoodTotal = `-- name: ViewFoodTotal :one
SELECT 
  SUM(calories)::float as total_calories,
  SUM(protein)::float as total_protein,
  SUM(carbs)::float as total_carbs,
  SUM(fats)::float as total_fats
FROM food_entries
WHERE user_id = $1 
  AND created_at BETWEEN $2 AND $3
`

type ViewFoodTotalParams struct {
	UserID      int64            `json:"user_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

type ViewFoodTotalRow struct {
	TotalCalories float64 `json:"total_calories"`
	TotalProtein  float64 `json:"total_protein"`
	TotalCarbs    float64 `json:"total_carbs"`
	TotalFats     float64 `json:"total_fats"`
}

func (q *Queries) ViewFoodTotal(ctx context.Context, arg ViewFoodTotalParams) (ViewFoodTotalRow, error) {
	row := q.db.QueryRow(ctx, viewFoodTotal, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	var i ViewFoodTotalRow
	err := row.Scan(
		&i.TotalCalories,
		&i.TotalProtein,
		&i.TotalCarbs,
		&i.TotalFats,
	)
	return i, err
}
